services:
  vm:
    image: ghcr.io/ctrsploit/kubernetes-v1.32.2_containerd-v2.0.3_calico:v0.2.0
    environment:
      - "QEMU_NET=10.0.2.0/24"
      - "QEMU_DHCPSTART=10.0.2.16"
      - "QEMU_HOSTFWD=hostfwd=tcp::6443-:6443"
    ports:
        - "13512:22"
        - "13513:6443"
    tty: true
    stdin_open: true 

