services:
  vm:
    image: ghcr.io/ctrsploit/podman-v5.4.0:v0.1.0
    # Use host cpu to fix: "Fatal glibc error: CPU does not support x86-64-v2"
    command: /start.sh -cpu host
    ports:
        - "54000:22"
    tty: true
    stdin_open: true
