# ================================
# Configuration Variables
# ================================
ARG VERSION_UBUNTU_BASE=v0.3.0

# ================================
# Internal Variables
# ================================
ARG BASE_IMAGE=ghcr.io/ctrsploit/ubuntu-22.04:ctr_${VERSION_UBUNTU_BASE}

# ================================
# Build Stages
# ================================
FROM ${BASE_IMAGE} AS build
