services:
  vm:
    image: ghcr.io/ctrsploit/harbor-v2.15.2:v0.1.21
    environment:
      - "QEMU_HOSTFWD=hostfwd=tcp::80-:80"
    ports:
        - "21520:22"
        - "21521:80"
    tty: true
    stdin_open: true
