package embedded

import (
	_ "embed"

	"github.com/ctrsploit/dqd/cli/internal/catalog"
)

// The snapshot under live/ is generated by `dqd-gen embed` and
// COMMITTED (like catalog.json and ssh_config/config), so that
// `go install github.com/ctrsploit/dqd/cli/cmd/dqd@latest` produces
// a fully self-contained binary. `make check-catalog` verifies its
// freshness.

//go:embed live/index.json
var indexJSON []byte

//go:embed live/tree.json
var treeJSON []byte

func init() {
	var err error
	Index, err = catalog.ParseIndex(indexJSON)
	if err != nil {
		panic("embedded: broken live index (run `dqd-gen embed`): " + err.Error())
	}
	Tree, err = catalog.ReadTree(treeJSON)
	if err != nil {
		panic("embedded: broken live tree (run `dqd-gen embed`): " + err.Error())
	}
}
